### ISSUE TITLE
バグというわけではないのですが…

### ISSUE THREAD

**Issue by landcelita** [Tatamo/atcoder-cli#38]
http://tatamo.81.la/blog/2018/12/07/atcoder-cli-tutorial/　のデフォルト動作の説明のページのacc cnfig -hはacc config -hではないでしょうか？　それと素晴らしいツールありがとうございます！まさに探していたツールです

**Comment by Tatamo** [comment]
報告していただきありがとうございます。修正しました。
こちらこそ使っていただいてありがとうございます。
