### ISSUE TITLE
loginコマンド時にオプションでユーザー名、パスワードを渡せるようにする

### ISSUE THREAD

**Issue by hinamimi** [Tatamo/atcoder-cli#44]
素晴らしいツールの開発・メンテナンスありがとうございます。1年近く利用させて頂いています。  

docker containerでAtCoder用の環境を作り、その中で利用しているのですが、ユーザー名・パスワードを毎回打つのが面倒に感じています。online-judge-toolsのように以下のようなログインオプションがあったら、嬉しく存じます。

```
$ acc login --help             
Usage: index login [options]

login to AtCoder

Options:
  -u, --username <username>  your username
  -p, --password <password>  your password
  -h, --help                 output usage information
```

**Comment by Tatamo** [comment]
コマンドにパスワードを渡す場合、`~/.history` や `~/.bash_history`, `~/.zsh_history` といったローカルファイルにコマンド履歴としてパスワードが残る可能性が高い点が懸念されるかなと思っています。

`acc config-dir` コマンドを使用すると設定ファイルが配置されているディレクトリのパスが表示されますので、
```
cd `acc config-dir`
```
として設定ディレクトリに移動すると、設定ファイルである `config.json` に加えて `session.json` が配置されていると思います(既にログインしている場合)。
atcoder-cli ではこちらのファイルを使ってログイン状態を保存しています。
パスワードをそのままローカルファイルとして保存するよりも、ログインセッションのみ保存するほうがよいと考えているためです。
コンテナ内で `acc config-dir` を実行して得られる場所にボリュームをマウントしてホストマシンの `session.json` を共有できるようにしたり、予めどこかでログインして用意しておいた `session.json` をコンテナに含めることでログイン状態を保持できるのではないかと思うのですが、一度そちらが可能かどうか検討していただけますでしょうか。

**Comment by Tatamo** [comment]
こちら提案させていただいた方法で問題が解決できそうでしょうか？
とくに返信がなければ、この issue は適当に時期を見て PR と一緒に close させていただこうと思います。
atcoder-cli をいつも利用していただいていてありがとうございます、引き続きよろしくお願いします。

**Comment by hinamimi** [comment]
問題自体は解決しました、closeしておきます。大変素晴らしいサービスのメンテナンスありがとうございます。
