### ISSUE TITLE
acc submit の際に "... no samples were downloaded ..." という警告がでる件について

### ISSUE THREAD

**Issue by ktrarai** [Tatamo/atcoder-cli#46]
とても便利なツールを開発・公開してくださりありがとうございます。

さて、表題の件ですが、 `acc submit` を実行すると

```
[WARNING] the problem "https://atcoder.jp/contests/abc101/tasks/abc101_b" is specified to submit, but no samples were downloaded in this directory. this may be mis-operation
Are you sure? Please type "abcb"
```

のようになり、 `abcb` などとタイプしないと提出できないのがわずかにですがわずらわしいです。

この件についてこちらに投稿することが適切でなければ申し訳ありませんが、これは online-judge-tools との依存関係に由来する仕様との理解でよろしいでしょうか。

online-judge-tools では ~/.cache/online-judge-tools/download-history.jsonl に該当するダウンロード履歴が記録されていないとこの警告が出る模様です。

そして oj/onlinejudge_command/subcommand/download.py の 134 行目で

https://github.com/online-judge-tools/oj/blob/70f8a29ae6a1f551fee50b35b61354ccbc81505f/onlinejudge_command/subcommand/download.py#L134

などとあって、 `oj` コマンドの呼び出し書式がデフォルトの場合にダウンロード履歴を記録する仕様のようです。

実際、初心者でよくわからないなりにコードを拝見し、

atcoder-cli/src/project.ts 194 行目

https://github.com/Tatamo/atcoder-cli/blob/f385e71ba270716f5a94e3ed9bd23a24f78799d0/src/project.ts#L194

を

```typescript
                        await OnlineJudge.call(["dl", task.url]);
```

と改変し手元の環境でビルドしなおして実行してみたところ、上記の警告はなくなり `[y/N]` というプロンプトになりました。

しかし、このように修正してしまうとサンプル ケースを配置するディレクトリ名を変更できなくなるので、やはり本件は仕様ということでしょうか。

お時間に余裕のあるときにでも作者様のご意見をいただければ幸いです。

以上、よろしくお願いいたします。

**Comment by ktrarai** [comment]
> atcoder-cli/src/project.ts 194 行目
> 
> https://github.com/Tatamo/atcoder-cli/blob/f385e71ba270716f5a94e3ed9bd23a24f78799d0/src/project.ts#L194
> 
> を
> 
> ```ts
>                         await OnlineJudge.call(["dl", task.url]);
> ```
> 
> と改変し手元の環境でビルドしなおして実行してみたところ、上記の警告はなくなり `[y/N]` というプロンプトになりました。
> 
> しかし、このように修正してしまうとサンプル ケースを配置するディレクトリ名を変更できなくなるので、やはり本件は仕様ということでしょうか。

後から思いついた浅知恵ですが

```typescript
                        /*
                                oj dl は -f, -d オプションを指定しない場合にダウンロード履歴を
                                記録する。ダウンロード履歴がないと oj s の際に警告が出る。
                                testdir が空になるように template / config を設定することにより
                                oj dl を -d オプションなしで呼び出せるようにする。
                        */
                        if (testdir) {
                                await OnlineJudge.call(["dl", task.url, "-d", testdir]);
                        } else {
                                await OnlineJudge.call(["dl", task.url]);
                        }
```

とすれば、他の部分への影響を抑えつつ、当該の警告が出ないようにしたいというこちらの希望も実現できると思いますが、いかがでしょう。 (既に検討済みで本件の対応は見送られていたのでしたら、大変失礼いたしました。所詮、初心者の浅知恵につき、ご容赦ください。)

**Comment by Tatamo** [comment]
https://github.com/Tatamo/atcoder-cli/pull/9
https://github.com/online-judge-tools/oj/issues/336

この問題自体は認識しているもので、以前検討した結果としては
https://github.com/Tatamo/atcoder-cli/pull/26 のように

```
$acc submit -s -- -y
```

と入力することで、 oj コマンド側に `-y` オプションを渡すことでこの確認をスキップする、という対応となっています。
たしかにデフォルトで毎回入力を求められる挙動が煩雑ではあるのですが、どちらかというと online-judge-tools 側の挙動に起因するものであり、そちらでは対応を行わないという結論が出ているため対処が難しい状況です。

ちなみに oj コマンドにパラメータを渡さないと `tests` ではなく `test` フォルダが生成されるようになっていると思います。
たしかに atcoder-cli 側のデフォルトを `test` に変えてしまえば提案していただいた方法で済む話ではあるのですが、後方互換性を壊す変更になってしまうため躊躇しているところです……

**Comment by ktrarai** [comment]
丁寧なご回答をありがとうございます。また、いろいろ大変申し訳ございませんでした。 atcoder-cli の機能や使い勝手をとても気に入っておりますので、今後とも、一ユーザーとして、よろしくお願いいたします。

**Comment by Tatamo** [comment]
こちらこそ、利用していただきありがとうございます。引き続き何かありましたらよろしくお願いします。
