### ISSUE TITLE
`acc new abc~` で作成されるサンプルケースのディレクトリが `tests`になっており、`online-judge-tools`と同時に使えない。

### ISSUE THREAD

**Issue by Yuta123456** [Tatamo/atcoder-cli#54]
初めてIssueを書くので、不手際があったらすみません。
本日`atcoder-cli`をインストールして使ってみたのですが、どうやら、`acc new abc~` で作成されるサンプルケースの名前が`tests`になっており、一方`online-judge-tools`では `test`フォルダに対してチェックを行っているようで、
```
[WARNING] the problem "https://atcoder.jp/contests/abc190/tasks/abc190_a" is specified to submit, but no samples were downloaded in this directory. this may be mis-operation
```
このように表示されます。
どこか設定等間違っていれば教えていただければ幸いです。

**Comment by Tatamo** [comment]
atcoder-cli を使用していただきありがとうございます。
#46 でも確認している問題で、現状 WARNING が出ても問題はなく、プロンプトに沿って問題IDを入力していただくことで提出できるようになっています。

oj 側でこの挙動について変更を加える予定はないと伺っていますので、atcoder-cli 側で対応を検討してみます。
* テンプレートで testDir の値が "test" だった場合のみ、 oj に -d オプションを渡さない (ref: https://github.com/online-judge-tools/oj/issues/336)
* `acc config` で設定できる項目に 「oj デフォルトのテストディレクトリを使う」のオプションを追加する

このどちらかを実施すれば後方互換性を壊さずに対処できるかもしれません。

**Comment by Yuta123456** [comment]
なるほど、ご丁寧にありがとうございます。
承知しました。対応してみます。
> atcoder-cli を使用していただきありがとうございます。

こちらこそこんな便利なツールを作成していただきありがとうございます。
