### ISSUE TITLE
broken by the update of the domain of AtCoder

### ISSUE THREAD

**Issue by kmyk** [Tatamo/atcoder-cli#6]
先週の `beta.atcoder.jp` が `atcoder.jp` で置き換わったやつにより壊れてます

```
$ acc n abc001                   
Request failed with status code 301
```

**Comment by Tatamo** [comment]
修正しました。
バージョンアップ前に作成したコンテストディレクトリ内で`acc tasks` などを実行するとbetaがついたままのURLが取得されますが、問題追加などには影響が無いことを確認しています。
